### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by cloudfaction** [akeeba/plg_filesystem_s3#10]
### Steps to reproduce the issue
set up S3 connection

### Expected result
connection

### Actual result
Akeeba\Engine\Postproc\Connector\S3v4\Connector::internalGetBucket(): [60] SSL certificate problem: unable to get local issuer certificate

### Troubleshooting already performed
checked settings

### System information

* **Joomla! version**:  441
* **Joomla! backend template**: default
* **Joomla! frontend template**: default
* **PHP version**: 7.4
* **Browser (name and version)**: chrome

**Comment by nikosdion** [comment]
https://www.howtouselinux.com/post/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate

**Comment by nikosdion** [comment]
**Please** do your due diligence before filing non-issue tickets as bugs. Using a search engine to look up the error message would've gotten you to the same or a similar page than the one I linked you to. It so happens that I am kind enough to respond to a non-bug issue. Most FOSS projects would not even bother with something like that. They'd mark it invalid and go on their merry way.

Remember, the responsibility of FOSS is a two way street. Us maintainers are responsible for adding features and removing bugs so as not to waste the users' time, you the users are responsible for doing your due diligence before reporting a potential bug so as not to waste the maintainers' time. Thank you in advance.

**Comment by cloudfaction** [comment]
Nicholas, I am sorry for the inconvenience. Thank you for your time,
plugin and effort!

Met vriendelijke groet,

Cloudfaction, internetspecialisten

Maarten Blokdijk
Korenaar 55
3224XD Hellevoetsluis

M: 06 - 247 59 222
W: https://www.cloudfaction.nl
Volg ons op twitter: @cloudfaction


Kamer van Koophandel: 56770065




Op wo 10 jan 2024 om 10:19 schreef Nicholas K. Dionysopoulos <
***@***.***>:

**Comment by cloudfaction** [comment]
but i have a standard bucket on amazon, that i also use to store my akeeba
backups on, works fine and has worked fine for years!

And this will not connect.. hence my question.

Met vriendelijke groet,

Cloudfaction, internetspecialisten

Maarten Blokdijk
Korenaar 55
3224XD Hellevoetsluis

M: 06 - 247 59 222
W: https://www.cloudfaction.nl
Volg ons op twitter: @cloudfaction


Kamer van Koophandel: 56770065




Op wo 10 jan 2024 om 10:19 schreef Nicholas K. Dionysopoulos <
***@***.***>:

**Comment by cloudfaction** [comment]
Nicoals,

Tried it on another server and it works. This is a great plugin! thank you!

Met vriendelijke groet,

Cloudfaction, internetspecialisten

Maarten Blokdijk
Korenaar 55
3224XD Hellevoetsluis

M: 06 - 247 59 222
W: https://www.cloudfaction.nl
Volg ons op twitter: @cloudfaction


Kamer van Koophandel: 56770065




Op wo 10 jan 2024 om 10:19 schreef Nicholas K. Dionysopoulos <
***@***.***>:
