### ISSUE TITLE
Custom S3 - DreamObject S3 Bucket Name URL build problem

### ISSUE THREAD

**Issue by bcordis** [akeeba/plg_filesystem_s3#12]
### Steps to reproduce the issue
The DreamObject S3 URLs for the Site already included the Bucket name. Trying to save without the bucket name in them still failed to generate all the previews, and access to all the files is broken.
The URLs will pass to the src->adapter->S3Filesystem.php getFromConnection, and $connection['custom endpoint'] will eventually have HTTP/s included in the connection URL and fail as DreamObjects do not support connections with HTTP/HTTPS in them. 

### Expected result
There is no error when saving the server in the plugin. Stating the certificate has expired.

### Actual result
The error returned with the bucket name included in the URL.

### Troubleshooting already performed
In src->adapter->S3Filesystem.php getFromConnection and $connection['custom endpoint'], I tested by removing the https?:// from the string, and it connected. Then, I moved on to the bucket name included for the previews. I traced it down to /vendor/akeeba/s3/src/Request.php getHostName, thinking it needed to add the bucket name to the URL. I bypassed this by adding modifications to look for the URL with dream.io, as I could see no other options then.

After the modifications, the system returned files and preview images. I am still doing more debugging work on functions.

### System information

* **Joomla! version**: 5.1.0-beta2
* **Joomla! backend template**: Atum
* **Joomla! frontend template**: Cassiopeia
* **PHP version**: 8.3.0
* **Browser (name and version)**: Chrome 123.0.6312.59 (Official Build) (x86_64)

**Comment by nikosdion** [comment]
Use the following dev release [plg_filesystem_s3-1.1.1-dev202403251625-revc76643e.zip](https://github.com/akeeba/plg_filesystem_s3/files/14746721/plg_filesystem_s3-1.1.1-dev202403251625-revc76643e.zip)

For the necessary configuration please read https://github.com/akeeba/plg_filesystem_s3/blob/development/docs/3pd-config.md#dreamhost-dreamobjects
