### ISSUE TITLE
Cloudflare R2 compatible

### ISSUE THREAD

**Issue by alebak** [akeeba/plg_filesystem_s3#14]
**Is your feature request related to a problem?**

I am trying to use the plugin by configuring it for Cloudflare's R2 service but I get the following message: 

"AkeebaS3Connector::internalGetBucket(): [500] Unauthorized:SigV2 authorization is not supported. Please use SigV4 instead."

**Describe the solution you'd like**

That the plugin was compatible with Cloudflare's R2 service.

**Describe alternatives you've considered**

I have tried enabling and disabling the other options and changing the authentication mode from V4 to V2 and it does not work.

**Why do you think this is relevant to people other than you**

Cloudflare's R2 is also a service that is gaining prominence and popularity in cloud storage offerings with very competitive pricing versus DigitalOcean's AWS S3 and Space, two providers that I was able to set up and test the plugin with no issues. It's a matter of time for many people to start using it massively.

**Additional context**

I share with you the screenshots of my plugin configuration with the data for Cloudflare R2 and the error message I get.

![image](https://github.com/akeeba/plg_filesystem_s3/assets/6515879/83aeadee-26b4-451c-a45d-045057dc39ce)

![image](https://github.com/akeeba/plg_filesystem_s3/assets/6515879/a8b20876-54b7-4d73-a883-e56bc14edf97)

![image](https://github.com/akeeba/plg_filesystem_s3/assets/6515879/b43e3a9f-1d1d-47b6-8e01-79b8cb16076c)

**Comment by nikosdion** [comment]
First install this dev release: 
[plg_filesystem_s3-1.1.2-dev202404300821-rev452ca17.zip](https://github.com/akeeba/plg_filesystem_s3/files/15160452/plg_filesystem_s3-1.1.2-dev202404300821-rev452ca17.zip)

Then take a look at https://github.com/akeeba/plg_filesystem_s3/blob/development/docs/3pd-config.md#cloudflare-r2 for configuration instructions.

**Comment by alebak** [comment]
Thank you @nikosdion, the dev release it worked fine for R2! :raised_hands:

**Comment by nikosdion** [comment]
Awesome! Thank you for your feedback :)
