### ISSUE TITLE
Question: Can this be used for displaying a list of files in a bucket?

### ISSUE THREAD

**Issue by raspitakesovertheworld** [akeeba/plg_filesystem_s3#4]
Hi,

I'm trying to make  a mp3 podcast service on Joomla easier to manage: mp3s get recorded and then uploaded automatically to S3, so I want to display a list of all mp3 files in a S3 bucket in a Joomla article, so that people can listen to them / download them.
Can this be done with this plugin?

Thank you for your time.

**Comment by nikosdion** [comment]
Unfortunately not. This plugin only makes an S3 bucket appear as a "drive" in Joomla's Media Manager. You are looking for some kind of module which lists the contents of an S3 bucket, has a media player etc; that's a completely different kind of software, I'm afraid.

**Comment by raspitakesovertheworld** [comment]
It is simply for listing the directory of mp3 files on S3, nothing more. It does not need to have a media player, because that is included in the browser: if you click on a mp3 file, it gets downloaded and a player appears in the browser, this has gotten really easy thankfully.

**Comment by nikosdion** [comment]
As already explained, you are looking at the wrong software to solve your problem.

I am locking this thread now. Having to repeat the same thing multiple times is unproductive.
