### ISSUE TITLE
Access Key missing error

### ISSUE THREAD

**Issue by hammondwb** [akeeba/plg_filesystem_s3#5]
### Steps to reproduce the issue
Install the Filesystem - Amazon S3 plugin.
Go to the the plugin and click to create a connection. 
Fill out the form, including the AWS Access Key you created in AWS.
Save the form,

### Expected result
Successful saving of the connection.

### Actual result
Throws error: Joomla\CMS\Form\Form::validateField() rule `AccessKey` missing.
Connection doesn't save.

### Troubleshooting already performed
Confirmed an access key was added. 

### System information

* **Joomla! version**: 3.10.12.
* **Joomla! backend template**: isis
* **Joomla! frontend template**: jb_bobby
* **PHP version**: 7.4.33
* **Browser (name and version)**: Chrome 115.0.5790.110 (Official Build) (64-bit)

**Comment by nikosdion** [comment]
The plugin does not support Joomla! 3. The whole concept of filesystem provider plugins for the Joomla! Media Manager —what this plugin implements— is one of the new Joomla 4 features.
