### ISSUE TITLE
Validation issue with AccessKey

### ISSUE THREAD

**Issue by hammondwb** [akeeba/plg_filesystem_s3#6]
### Steps to reproduce the issue
Install the plugin. 
Create a new connection.
Fill in fields.
Click Save

### Expected result
Create new connection.

### Actual result
Goes to error age with the following error:
Joomla\CMS\Form\Form::validateField() rule `AccessKey` missing.

### Troubleshooting already performed
Ensured access key was entered.
Comments out AccessKey validation in plugin's XML file. Error moved to the next field for SecretKey.

### System information
Joomla 3.10.12.
PHP 7.4.33

* **Joomla! version**: 3.10.12
* **Joomla! backend template**: 
* **Joomla! frontend template**: angry_bobby
* **PHP version**: 7.4.33
* **Browser (name and version)**: Chrome Version 116.0.5845.96 (Official Build) (64-bit)

**Comment by nikosdion** [comment]
This plugin only works with Joomla! 4 and 5.

Joomla! 3 does not have the Media Manager feature which allows for third party filesystem providers. It only works with files stored locally on your server.
