### ISSUE TITLE
nothing in the media manager

### ISSUE THREAD

**Issue by Philippe-FRICH** [akeeba/plg_filesystem_s3#7]
### Steps to reproduce the issue
I use Akeeba backups pro for my site backups with Amazon S3 post-processing. I use the services of my web host (planethoster) which provides third-party storage with an S3 compatible API. It works perfectly.
So I wanted to set up your "plg_filesystem_s3" plugin with exactly the same settings as for the post processing of Akeeba backups. I've tried multiple times and it doesn't work.

### Expected result
Have access to images stored in the public part of S3 storage

### Actual result
"Amazon S3" is indicated in the media manager but nothing else (apart from local and its directories as usual)

### Troubleshooting already performed
I thought there was a problem with admintools which I disabled but that didn't change anything.

### System information

* **Joomla! version**: 4.3.4
* **Joomla! backend template**: Atum
* **Joomla! frontend template**: created with template-creator
* **PHP version**: 8.1.18
* **Browser (name and version)**: Chrome v116.0.5845.96

**Comment by nikosdion** [comment]
How many files are in the root of that bucket?

**Comment by nikosdion** [comment]
Also, are they files the Media Manager would display? Remember, Media Manager only displays a very few file types. It will _NOT_ display JPA and JPS backup archive files for example. It's a **Media** Manager, not a **file** manager.

**Comment by Philippe-FRICH** [comment]
Only one png file (to try)

**Comment by Philippe-FRICH** [comment]
The jpa files are in the private part and the media in the public part

**Comment by nikosdion** [comment]
After a lot of testing I can tell you that there is no problem.

Joomla's Media Manager is a **media file** manager, not a generic file manager. It will only display the files which it knows are media files. Anything else is not listed. Therefore, if you expect it to list JPA files: it won't do it.

The same thing applies for _local_ folders. Go to System, Plugins, FileSystem - Local and add a folder which only has non-media files, e.g. ZIP files. When you choose that directory in the Media Manager you will see that its folders will appear "empty", even though there are files in those folders.

You are trying to use Joomla's Media Manager for something it was not designed to do. It's not an issue with this file provider plugin, it's how Joomla's Media Manager works.
